export const heliosEmployes = [
  {
    name: 'Ada Dud',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Ada Zag',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Aga Nag',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Ale Jed',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Ale Gra',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Ani Skr',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Art Chm',
    sex: 'male',
    bar1: false,
    bar2: false,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Bar Czo',
    sex: 'male',
    bar1: false,
    bar2: false,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Bar Gaz',
    sex: 'male',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Bar Klo',
    sex: 'male',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Bea Wol',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Dan Bal',
    sex: 'male',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Jul Rutk',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Jul Sta',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Jul Sto',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Kac Chm',
    sex: 'male',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Kar Kle',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Kas Tro',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Kub Mat',
    sex: 'male',
    bar1: false,
    bar2: false,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Mac Kuj',
    sex: 'male',
    bar1: false,
    bar2: false,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Nat Kur',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Nat Jar',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Ale Aft',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Ale Rud',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Ale Rum',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Olg Maj',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: false,
    obs2: false,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Pat Fed',
    sex: 'male',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Paw Dec',
    sex: 'male',
    bar1: false,
    bar2: false,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Pio Kon',
    sex: 'male',
    bar1: false,
    bar2: false,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Pio Mil',
    sex: 'male',
    bar1: false,
    bar2: false,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Rok Gom',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Wer Gał',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: false,
    obs2: false,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Wik Sak',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: false,
    obs2: false,
    coffee: true,
    tickets: true,
  },
  {
    name: 'Zos Rut',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
  {
    name: 'Zuz Sów',
    sex: 'female',
    bar1: true,
    bar2: true,
    obs1: true,
    obs2: true,
    coffee: false,
    tickets: true,
  },
];
